# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e88c65401870f9fd3a4356a93ba7755ff0ec51bc9e0f7806c4d829284dcb42b1921c5b1753fc39407f87d2b1c8dc89087c2a311a27d97324c71de13c17818d32

test:
  secret_key_base: cf4f28f8bfdd5eeb96419effdf66bc8f73ecc33ee1fecb0ce215aa151caba281d9d09d0ae4255164775f5acc430b093eaa42d0329ccdb03b361aa5111314aca6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
